---
title: "Proyek Akhir Sentimen Analysis"
author: "Yohanes Ageng Hendrawan Zhamudra Putra"
date: "11/28/2022"
output:
  word_document: default
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## 1. Import library yang dibutuhkan
```{r library}
# Install
#install.packages("tm")  # for text mining
#install.packages("SnowballC") # for text stemming
#install.packages("wordcloud") # word-cloud generator 
#install.packages("RColorBrewer") # color palettes
#install.packages("syuzhet") # for sentiment analysis
#install.packages("ggplot2") # for plotting graphs
# Load
library("tm")
library("janeaustenr")
library("stringr")
library("stringr")
library("stringr")
library("dplyr")
library("SnowballC")
library("wordcloud")
library("reshape2")
library("RColorBrewer")
library("syuzhet")
library("shiny")
library("tidyverse")
library("tidytext")
library("ggplot2")
library("plotly")
```

## 1. Import file
```{r}
reviews_amazon = read.csv("amazon_reviews.csv")
reviews_amazon = sample_n(reviews_amazon, 1000)

str(reviews_amazon)
```
## 3. Data exploratory
### 3.1. Rata rata score berdasarkan versi aplikasi

```{r}
reviews_amazon %>%
  group_by(Score) %>% summarise(n=n()) %>% arrange(desc(n))
  
```

```{r}
reviews_amazon %>%
  group_by(Score) %>% summarise(n=n()) %>% arrange(desc(n)) %>%
  ggplot(aes(x=Score, y=n)) + geom_col() + labs(x = "Star", 
                                                    y = "Total Skor", 
                                                    title = "Grafik perhitungan review", 
                                                    subtitle = "Rata rata score berdasarkan star review") + coord_flip()
  
```

## 3. Data cleansing
```{r}
cleansing = function(text){
  text = text %>% 
    tolower() %>% 
    removeNumbers() %>% 
    removeWords(stopwords(kind = "en")) %>% 
    removePunctuation() %>% 
    stripWhitespace() %>% 
    stemDocument()
}
reviews_amazon$Summary = sapply(reviews_amazon$Summary, cleansing)
head(reviews_amazon$Summary)
```

## 4. Text Analysis
```{r}
amazon_text <- Corpus(VectorSource(reviews_amazon$Summary))
# Build a term-document matrix
amazon_text_dtm <- TermDocumentMatrix(amazon_text)
dtm_m <- as.matrix(amazon_text_dtm)
# Sort by descearing value of frequency
dtm_v <- sort(rowSums(dtm_m),decreasing=TRUE)
dtm_d <- data.frame(word = names(dtm_v),freq=dtm_v)
# Display the top 5 most frequent words
head(dtm_d, 5)
```
## 5. Most Frequent Word
```{r}
barplot(dtm_d[1:5,]$freq, las = 2, names.arg = dtm_d[1:5,]$word,
        col ="lightgreen", main ="Top 5 most frequent words",
        ylab = "Word frequencies")
```
## 5.2 Most Frequent Word wordcloud
```{r}
#generate word cloud
set.seed(1234)
wordcloud(words = dtm_d$word, freq = dtm_d$freq, min.freq = 5,
          max.words=100, random.order=FALSE, rot.per=0.40, 
          colors=brewer.pal(8, "Dark2"))
```



## 6. Sentimen analysis
```{r}
# regular sentiment score using get_sentiment() function and method of your choice
# please note that different methods may have different scales
Amazon_sentiment <- get_sentiment(reviews_amazon$Summary, method="syuzhet")
# see the first row of the vector
head(Amazon_sentiment)
# see summary statistics of the vector
summary(Amazon_sentiment)

```

### 6.1. Emotion classification
```{r}
# run nrc sentiment analysis to return data frame with each row classified as one of the following
# emotions, rather than a score: 
# anger, anticipation, disgust, fear, joy, sadness, surprise, trust 
# It also counts the number of positive and negative emotions found in each row
amazon_emotion_sentiment<-get_nrc_sentiment(reviews_amazon$Summary)

# head(data_sentiment,10) - to see top 10 lines of the get_nrc_sentiment dataframe
head (amazon_emotion_sentiment)
```

### 6.2.Sentiment visualization
```{r echo=FALSE}
#transpose
td<-data.frame(t(amazon_emotion_sentiment))
#The function rowSums computes column sums across rows for each level of a grouping variable.
td_new <- data.frame(rowSums(td[2:100]))
#Transformation and cleaning
names(td_new)[1] <- "count"
td_new <- cbind("sentiment" = rownames(td_new), td_new)
rownames(td_new) <- NULL
```

```{r}
td_new2<-td_new[1:8,]
#Plot One - count of words associated with each sentiment
quickplot(sentiment, data=td_new2, weight=count, geom="bar", fill=sentiment, ylab="count")+ggtitle("Survey sentiments")

```

```{r}
quickplot(sentiment, data=td_new[9:10,], weight=count, geom="bar", fill=sentiment, ylab="count")+ggtitle("Survey sentiments")
```

## 7. Shiny 
```{r}
option_parameter <- colnames(data_sentiment)[-c(1, 2)]
option_parameter
```

```{r ui}
ui = navbarPage(
  title = "Shini-box",
  inverse = T,
  tabPanel(
    title = "Word Frequency",
    fluidPage(
  
      fluidRow(
        column(
          4,
          h3("Total Reviews"),
          h4(strong(textOutput(outputId = "total_reviews")))
        ),
        column(
          4,
          h3("Positive Words"),
          h4(strong(textOutput(outputId = "total_positive")))
        ),
        column(
          4,
          h3("Negative Words"),
          h4(strong(textOutput(outputId = "total_negative")))
        )
      ),
  
      sidebarLayout(
        sidebarPanel(
          textInput(
            inputId = "count",
            label = "Word count",
            value = "5"
          )
        ),
        
        mainPanel(
          plotlyOutput(outputId = "plot_word_freq", height = "700px")
        )
      )
    )
  ),
  tabPanel(
    title = "WordCloud",
    fluidPage(
      mainPanel(
        h3("Words Cloud", align = "center"),
        plotOutput(outputId = "plot_word_cloud", width = "100%"),
      )
    )
  ),
  tabPanel(
    title = "Sentiment analysis",
    fluidPage(
      fluidRow(
        column(
          4,
          h3("Total Anger"),
          h4(strong(textOutput(outputId = "total_ang")))
        ),
        column(
          4,
          h3("Total Anticipation"),
          h4(strong(textOutput(outputId = "total_ant")))
        ),
        column(
          4,
          h3("Total Disgust"),
          h4(strong(textOutput(outputId = "total_dis")))
        ),
        column(
          4,
          h3("Total Fear"),
          h4(strong(textOutput(outputId = "total_fear")))
        ),
        column(
          4,
          h3("Total Joy"),
          h4(strong(textOutput(outputId = "total_joy")))
        ),
        column(
          4,
          h3("Total Sadness"),
          h4(strong(textOutput(outputId = "total_sad")))
        ),
        column(
          4,
          h3("Total Surprise"),
          h4(strong(textOutput(outputId = "total_sur")))
        ),
        column(
          4,
          h3("Total Trust"),
          h4(strong(textOutput(outputId = "total_trust")))
        )
      ),
      
      mainPanel(
        h3("Sentiment", align = "center"),
        plotOutput(outputId = "plot_sentiment", width = "100%")
      )
    )
  )
  
  
  
)
```

```{r server}
server = function(input, output, session){
  output$total_reviews = renderText({
    reviews_amazon %>% nrow()
  })
  output$total_ant = renderText({
    td_new$count[2]
  })
  
  output$total_dis = renderText({
    td_new$count[3]
  })
  
  output$total_fear = renderText({
    td_new$count[4]
  })
  
  output$total_joy = renderText({
    td_new$count[5]
  })
  
  output$total_sad = renderText({
    td_new$count[6]
  })
  
  output$total_sur = renderText({
    td_new$count[7]
  })
  
  output$total_trust = renderText({
    td_new$count[8]
  })
  
  output$total_ang = renderText({
    td_new$count[1]
  })
  
  output$total_positive = renderText({
    td_new$count[10]
  })
  
  output$total_negative = renderText({
    td_new$count[9]
  })
  
  plot_word_freq = reactive({
    head(amazon_wordcounts, as.numeric(input$count) ) %>%
      ggplot(aes(x = word, y = n)) +
        geom_bar(stat = "identity") +
        coord_flip() +
        labs(
          x = "Words",
          y = "Frequency",
          title = "Word Frequency Graphic"
        ) +
        theme_light()
  })
  output$plot_word_freq = renderPlotly({
    ggplotly(plot_word_freq())
  })
  
  output$plot_word_cloud = renderPlot({
    set.seed(1234)
          wordcloud(words = dtm_d$word, freq = dtm_d$freq, min.freq = 5,
          max.words=100, random.order=FALSE, rot.per=0.40, 
          colors=brewer.pal(8, "Dark2"))
  })
  
  output$plot_sentiment = renderPlot({
    quickplot(sentiment, data=td_new2, weight=count, geom="bar", fill=sentiment, ylab="count")
  })
}
```

```{r run-app}
shinyApp(ui = ui, server = server)
```